include("${UTILS}")

get_build_platform(APP_PLATFORM_NAME)

set(APP_VERSION_YEAR ${BUILD_VERSION_YEAR})
set(APP_VERSION_NUMBER ${BUILD_VERSION_NUMBER})
set(APP_VERSION_STR "${APP_VERSION_YEAR}.${APP_VERSION_NUMBER}")
set(GIT_DESCRIBE "${APP_VERSION_STR}")
set(APP_PLATFORM_NAME "${BUILD_PLATFORM_NAME}")

configure_file("${SRC}" "${DST}" @ONLY)
